app/models.py
from . import db, bcrypt
from flask_login import UserMixin
from datetime import datetime
from sqlalchemy import CheckConstraint
from app.utils import generate_search_id, encrypt_url, decrypt_url


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)
    search_id = db.Column(db.String(10), unique=True, nullable=False)
    avatar_url = db.Column(db.String(255), nullable=True)
    mood_stamp_id = db.Column(db.Integer, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    # search_idのユニーク生成
    @staticmethod
    def generate_unique_search_id(session, length=10):
        while True:
            candidate = generate_search_id(length)
            exists = session.query(User).filter_by(search_id=candidate).first()
            if not exists:
                return candidate
            
    # passwordが8文字以上であることを確認し、ハッシュ化して保存
    def set_password(self, password):
        if len(password) < 8:
            raise ValueError("Password too short") #raiseで例外発生＆その後の処理を中断
        self.password_hash = bcrypt.generate_password_hash(password).decode('utf-8')
    
    # ログイン時passwordの検証
    def check_password(self, password):
        return bcrypt.check_password_hash(self.password_hash, password)
    

class Friend(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    friend_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=True)
    
    __table_args__ = (
        CheckConstraint("user_id != friend_id", name="check_user_not_friend"),
    )

class Talk_Member(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    talk_id = db.Column(db.Integer, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow)

class Talk(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
class Message(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    talk_id = db.Column(db.Integer, db.ForeignKey("talk.id"), nullable=False)
    stamp_id = db.Column(db.Integer, nullable=True)
    scale = db.Column(db.Integer, nullable=True)
    # image_url = db.Column(db.String(255), nullable=True)
    # video_url = db.Column(db.String(255), nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    # __table_args__ = (
    #     CheckConstraint("scale >= 1 AND scale <= 5", name="check_scale_1_5"),
    # )
    
    # __table_args__ = (
    #     CheckConstraint(
    #         "(stamp_id IS NULL AND scale IS NULL) OR (stamp_id IS NOT NULL AND scale IS NOT NULL)",
    #         name="check_stamp_scale_set"
    #     ),
    # )
    

app/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_babel import Babel, gettext as _
from flask_bcrypt import Bcrypt

db = SQLAlchemy()
bcrypt = Bcrypt()
migrate = Migrate()

babel = Babel()

login_manager = LoginManager()
login_manager.login_view = "auth.login"


def create_app():
    from dotenv import load_dotenv
    load_dotenv()
    
    app = Flask(__name__)
    
    app.config["SECRET_KEY"] = os.getenv("SECRET_KEY", "dev")
    app.config["SQLALCHEMY_DATABASE_URI"] = os.getenv("DATABASE_URL", "sqlite:///app.db")
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

    app.config["BABEL_DEFAULT_LOCALE"] = os.getenv("BABEL_DEFAULT_LOCALE", "ja")
    app.config["BABEL_DEFAULT_TIMEZONE"] = os.getenv("BABEL_DEFAULT_TIMEZONE", "Asia/Tokyo")

    #拡張機能初期化
    db.init_app(app)
    bcrypt.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)
    babel.init_app(app)
    
    from .models import User, Friend, Message, Talk, Talk_Member
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))
    app.jinja_env.globals['_'] = _

    #Blueprint
    from .routes import routes_bp
    from .auth.routes import auth_bp
    app.register_blueprint(routes_bp)
    app.register_blueprint(auth_bp)

    return app

app/routes.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user
from app.utils import encrypt_url, decrypt_url
from sqlalchemy import desc

routes_bp = Blueprint("routes", __name__)


@routes_bp.route("/", methods=['GET'])
def index():
    return render_template("main/individual-talk.html")


@routes_bp.route("/home", methods=['GET'])
@login_required
def home():
    # frieds = db.session.query(User).join(Friend, User.id == Friend.friend_id).filter(Friend.user_id == current_user.id).all()
    # context = {
    #     "user": current_user,
    #     "friends": frieds,
    # }
    # return render_template("main/home.html", **context)
    return render_template("main/home.html")


@routes_bp.route("/talks", methods=['GET'])
def talks(user_id):
    # current_userが所属するtalk_idのリストを取得
    user_talk_ids = db.session.query(Talk_Member.talk_id).filter(
        Talk_Member.user_id == current_user.id
    ).subquery()

    # 各talk_idのfriendユーザーの名前を取得
    talk_users = db.session.query(
        Talk_Member.talk_id,
        User.id,
        User.name
    ).join(User, Talk_Member.user_id == User.id).filter(
        Talk_Member.talk_id.in_(user_talk_ids),
        Talk_Member.user_id != current_user.id
    ).order_by(Talk.updated_at.desc())
    
    context = {
        "user": current_user,
        "messages": messages,
        "talk_users": talk_users,
    }
    return render_template("main/talks.html", **context)


@routes_bp.route("/individual-talk/<int:talk_id>", methods=['GET'])
def individual_talk(user_id, talk_id):
    messages = Message.query.filter_by(talk_id=talk_id).order_by(Message.created_at).all()
    
    talk_user = db.session.query(
        Talk_Member.talk_id,
        User.id,
        User.name
    ).join(User, Talk_Member.user_id == User.id).filter(
        Talk_Member.talk_id == talk_id,
        Talk_Member.user_id != current_user.id
    ).first()
    
    # # 登録フォームで動画URLを受け取り暗号化
    # image_url = request.form.get("image_url")
    # encrypted_image_url = encrypt_url(image_url) if image_url else None
    # video_url = request.form.get("video_url")
    # encrypted_video_url = encrypt_url(video_url) if video_url else None
    
    # # 暗号化されたURLを渡す
    # decrypted_image_url = decrypt_url(encrypted_image_url) if encrypted_image_url else None
    # decrypted_video_url = decrypt_url(encrypted_video_url) if encrypted_video_url else None
    
    context = {
        "user": current_user,
        "messages": messages,
        "talk_user": talk_user,
        # encrypted_image_url=encrypted_image_url,
        # encrypted_video_url=encrypted_video_url,
    }
    return render_template("main/individual-talk.html", **context)


@routes_bp.route("/settings")
def settings():
    return render_template("main/settings.html", user=current_user)

app/templates/index.html
{% extends "main/base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
  <h1>Welcome, {{ user.name }}!</h1>
  <a href="{{ url_for('auth.logout') }}">Logout</a>
{% endblock %}

app/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Stampy{% endblock %}</title>

  <link rel="stylesheet" href="{{ url_for('static', filename='css/sanitize.css') }}">
  <script src="https://cdn.tailwindcss.com"></script>
  <script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.8/dist/htmx.min.js"></script>

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Dela+Gothic+One&family=Noto+Sans+JP:wght@100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Potta+One&display=swap" rel="stylesheet">

</head>
<body class="bg-gray-100 text-gray-900">

  <!-- header -->
  <header class="w-full fixed top-0 left-0 right-0 bg-blue-500 text-white py-4 px-4 sm:px-10 shadow-lg">
    <div class="w-full flex items-center relative">
      <h1 class="text-3xl font-bold p-2">{{ _('Stampy') }}</h1>
      <h2 class="absolute left-1/2 -translate-x-1/2 text-3xl font-bold text-center">{% block page_title %}Page title{% endblock %}</h2>
    </div>
  </header>

  <!-- nav menu -->
  <nav class="fixed bottom-0 left-0 right-0 bg-white border-t-4 border-gray-200 shadow-2xl">
    <ul class="max-w-4xl mx-auto flex justify-around items-center p-4">
      <li class="inline-block text-center text-xs text-gray-700">
        <a href="{{ url_for('routes.home') }}">
          <img src="{{ url_for('static', filename='icons/main/home.svg') }}">
          <span>{{ _('ホーム') }}</span>
        </a>
      </li>
      <li class="inline-block text-center text-xs text-gray-700">
        <a href="{{ url_for('routes.talks') }}">
          <img src="{{ url_for('static', filename='icons/main/talk.svg') }}">
          <span>{{ _('トーク') }}</span>
        </a>
      </li>
      <li class="inline-block text-center text-xs text-gray-700">
        <a href="{{ url_for('routes.settings') }}">
          <img src="{{ url_for('static', filename='icons/main/setting.svg') }}">
          <span>{{ _('設定') }}</span>
        </a>
      </li>
    </ul>
  </nav>

  <!-- main -->
  <main class="min-h-screen overflow-y-auto max-w-2xl mx-auto bg-white pt-24 pb-20">
    {% block content %}{% endblock %}
  </main>
</body>
</html>

app/templates/main/home.html
{% extends "main/base.html" %}
{% block title %}Home{% endblock %}
{% block page_title %}{{ _('ホーム') }}{% endblock %}
{% block content %}

<div class="w-full px-8 py-4">

  <!-- myprofile -->
  <h2 class="text-xl font-bold mb-4 text-gray-800">{{ _('自分') }}</h2>
  <div class="bg-blue-200 rounded-3xl shadow-md py-4 px-8 mb-8">
    <div class="flex items-center justify-between">
      <p class="text-2xl font-bold text-gray-900">山田太郎</p>
      <div class="flex flex-col items-center align-middle">
        <p class="text-sm">今の気分</p>
        <img src="{{ url_for('static', filename='icons/mood/happy.svg') }}" alt="気分スタンプ" class="w-10 h-10">
        <a href="#" class="text-sm text-gray-600">{{ _('変更する') }}</a>
      </div>
    </div>
  </div>

  <!-- friends -->
  <h2 class="text-xl font-bold mb-4 text-gray-800">{{ _('友達') }}</h2>

  <div class="grid grid-cols-3 gap-6">
    <div class="bg-zinc-100 rounded-3xl shadow-md p-4 flex flex-col items-center overflow-hidden">
      <p class="w-full text-center text-xl font-bold text-gray-900 truncate">佐藤良子</p>
      <img src="{{ url_for('static', filename='icons/mood/happy.svg') }}" alt="気分スタンプ" class="w-10 h-10">
      <p class="text-sm">今の気分</p>    
    </div>
    <div class="bg-zinc-100 rounded-3xl shadow-md p-4 flex flex-col items-center overflow-hidden">
      <p class="w-full text-center text-xl font-bold text-gray-900 truncate">佐藤良子</p>
      <img src="{{ url_for('static', filename='icons/mood/happy.svg') }}" alt="気分スタンプ" class="w-10 h-10">
      <p class="text-sm">今の気分</p>    
    </div>
    <div class="bg-zinc-100 rounded-3xl shadow-md p-4 flex flex-col items-center overflow-hidden">
      <p class="w-full text-center text-xl font-bold text-gray-900 truncate">佐藤良子</p>
      <img src="{{ url_for('static', filename='icons/mood/happy.svg') }}" alt="気分スタンプ" class="w-10 h-10">
      <p class="text-sm">今の気分</p>    
    </div>
    <div class="bg-zinc-100 rounded-3xl shadow-md p-4 flex flex-col items-center overflow-hidden">
      <p class="w-full text-center text-xl font-bold text-gray-900 truncate">yamada michael kogorou</p>
      <img src="{{ url_for('static', filename='icons/mood/happy.svg') }}" alt="気分スタンプ" class="w-10 h-10">
      <p class="text-sm">今の気分</p>    
    </div>
    <div class="bg-zinc-100 rounded-3xl shadow-md p-4 flex flex-col items-center overflow-hidden">
      <p class="w-full text-center text-xl font-bold text-gray-900 truncate">田中正子</p>
      <img src="{{ url_for('static', filename='icons/mood/happy.svg') }}" alt="気分スタンプ" class="w-10 h-10">
      <p class="text-sm">今の気分</p>    
    </div>
    <div class="bg-zinc-100 rounded-3xl shadow-md p-4 flex flex-col items-center overflow-hidden">
      <p class="w-full text-center text-xl font-bold text-gray-900 truncate">田中正子</p>
      <img src="{{ url_for('static', filename='icons/mood/happy.svg') }}" alt="気分スタンプ" class="w-10 h-10">
      <p class="text-sm">今の気分</p>    
    </div>
    <div class="bg-zinc-100 rounded-3xl shadow-md p-4 flex flex-col items-center overflow-hidden">
      <p class="w-full text-center text-xl font-bold text-gray-900 truncate">田中正子</p>
      <img src="{{ url_for('static', filename='icons/mood/happy.svg') }}" alt="気分スタンプ" class="w-10 h-10">
      <p class="text-sm">今の気分</p>    
    </div>
  </div>

</div>



{% endblock %}

app/templates/main/individual-talk.html
{% extends "main/base.html" %}
{% block title %}Home{% endblock %}
{% block page_title %}{{ _('トーク') }}{% endblock %}
{% block content %}

<div class="w-full px-8 py-4">

  <div class="flex items-center mb-4">
    <p class="w-1/2 flex justify-center text-lg font-bold text-gray-900">山田花子</p>
    <p class="w-1/2 flex justify-center text-lg font-bold text-gray-900">工藤静香</p>
  </div>

  <div class="flex justify-between p-4 mb-4">
    <div class="w-1/2 flex flex-col items-center">
      <div class="w-full flex justify-start mb-2">
        <p class="text-sm">2/10 10:48</p>
      </div>
      <div class="flex flex-col items-center">
        <img src="{{ url_for('static', filename='icons/mood/happy.svg') }}" alt="気分スタンプ" class="w-10 h-10">
        <p class="text-sm mb-2">嬉しい</p>
        <div class="w-24 h-6 bg-gray-200 rounded-lg mb-2">
          <span name="scale" class="block w-1/3 h-6 bg-green-200 rounded-lg flex items-center justify-center text-center text-xs">{{ _('少し')}}</span>
        </div>
      </div>
    </div>
    <div class="w-1/2 flex flex-col items-center">
      <div class="w-full flex justify-end mb-2">
        <p class="text-sm">2/10 10:48</p>
      </div>
      <div class="flex flex-col items-center">
        <img src="{{ url_for('static', filename='stamps/read/read.png') }}" alt="既読スタンプ" class="w-10 h-10">
        <p class="text-sm mb-2">見たよ</p>
        <div class="mb-2">
          <button class="border border-gray-300 text-xs px-2 py-1 rounded-md">{{ _('リアクションする')}}</button>
        </div>
      </div>
    </div>
  </div>

  <div class="flex justify-between p-4 mb-4">
    <div class="w-1/2 flex flex-col items-center">
      <div class="w-full flex justify-start mb-2">
        <p class="text-sm">2/10 10:48</p>
      </div>
      <div class="flex flex-col items-center">
        <img src="{{ url_for('static', filename='icons/mood/fun.svg') }}" alt="気分スタンプ" class="w-10 h-10">
        <p class="text-sm mb-2">楽しい</p>
        <div class="w-24 h-6 bg-gray-200 rounded-lg mb-2">
          <span name="scale" class="block w-3/3 h-6 bg-green-200 rounded-lg flex items-center justify-center text-center text-xs">{{ _('とても')}}</span>
        </div>
      </div>
    </div>
    <div class="w-1/2 flex flex-col items-center">
      <div class="w-full flex justify-end mb-2">
        <p class="text-sm">2/10 10:48</p>
      </div>
      <div class="flex flex-col items-center">
        <img src="{{ url_for('static', filename='stamps/reaction/like.png') }}" alt="いいね" class="w-10 h-10">
        <p class="text-sm mb-2">いいね</p>
        <div class="mb-2">
          <button class="border border-gray-300 text-xs px-2 py-1 rounded-md">{{ _('リアクションを変更')}}</button>
        </div>
      </div>
    </div>
  </div>

  <div class="flex justify-between p-4 mb-4">
    <div class="w-1/2 flex flex-col items-center">
      <div class="w-full flex justify-start mb-2">
        <p class="text-sm">2/10 10:48</p>
      </div>
      <div class="flex flex-col items-center">
        <img src="{{ url_for('static', filename='stamps/read/be_read.png') }}" alt="既読スタンプ" class="w-10 h-10">
        <p class="text-sm mb-2">見たよ</p>
      </div>
    </div>
    <div class="w-1/2 flex flex-col items-center">
      <div class="w-full flex justify-end mb-2">
        <p class="text-sm">2/10 10:48</p>
      </div>
      <div class="flex flex-col items-center">
        <img src="{{ url_for('static', filename='icons/mood/bored.svg') }}" alt="気分スタンプ" class="w-10 h-10">
        <p class="text-sm mb-2">暇</p>
        <div class="w-24 h-6 bg-gray-200 rounded-lg mb-2">
          <span name="scale" class="block w-2/3 h-6 bg-green-200 rounded-lg flex items-center justify-center text-center text-xs">{{ _('普通')}}</span>
        </div>
      </div>
    </div>
  </div>


</div>



{% endblock %}

app/templates/main/settings.html
{% extends "main/base.html" %}
{% block title %}Home{% endblock %}
{% block content %}

<div class="max-w-4xl mx-auto">
  <h1 class="text-3xl font-bold text-center">ホーム</h1>
</div>

<div class="max-w-4xl mx-auto p-6">
  <!-- myprofile -->
  <div class="bg-white rounded-3xl shadow-xl p-8 mb-8">
    <h2 class="text-2xl font-bold mb-6 text-gray-800">{{ _('プロフィール') }}</h2>
    <div class="flex items-center gap-6">
      <p class="text-3xl font-bold text-gray-900 mb-2">山田太郎</p>
      <p class="text-2xl">今日の気分：{mood_stamp}</p>
    </div>
  </div>

  <!-- friends -->
  <h2 class="text-2xl font-bold mb-6 text-gray-800">{{ _('友達') }}</h2>
  <div class="flex flex-col gap-6 bg-white rounded-3xl shadow-xl p-8">
    <div class="flex items-center gap-6">
      <p class="text-3xl font-bold text-gray-900 mb-2">山田太郎</p>
      <p class="text-2xl">今日の気分：{mood_stamp}</p>
    </div>
  </div>
</div>



{% endblock %}

app/templates/main/talks.html
{% extends "main/base.html" %}
{% block title %}Home{% endblock %}
{% block page_title %}{{ _('トーク') }}{% endblock %}
{% block content %}

<div class="w-full px-8 py-4">

  <div class="bg-zinc-100 rounded-3xl shadow-md py-4 px-8 mb-4">
    <div class="flex items-center justify-between">
      <p class="text-2xl font-bold text-gray-900">山田花子</p>
      <div class="flex flex-col items-center align-middle">
        <img src="{{ url_for('static', filename='icons/mood/happy.svg') }}" alt="気分スタンプ" class="w-10 h-10">
        <p class="text-sm">2/10 10:48</p>
      </div>
    </div>
  </div>
  <div class="bg-zinc-100 rounded-3xl shadow-md py-4 px-8 mb-4">
    <div class="flex items-center justify-between">
      <p class="text-2xl font-bold text-gray-900">山田花子</p>
      <div class="flex flex-col items-center align-middle">
        <img src="{{ url_for('static', filename='icons/mood/happy.svg') }}" alt="気分スタンプ" class="w-10 h-10">
        <p class="text-sm">2/10 10:48</p>
      </div>
    </div>
  </div>
  <div class="bg-zinc-100 rounded-3xl shadow-md py-4 px-8 mb-4">
    <div class="flex items-center justify-between">
      <p class="text-2xl font-bold text-gray-900">山田花子</p>
      <div class="flex flex-col items-center align-middle">
        <img src="{{ url_for('static', filename='icons/mood/happy.svg') }}" alt="気分スタンプ" class="w-10 h-10">
        <p class="text-sm">2/10 10:48</p>
      </div>
    </div>
  </div>

</div>



{% endblock %}

templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Stampy{% endblock %}</title>

  <link rel="stylesheet" href="{{ url_for('static', filename='css/sanitize.css') }}">
  <script src="https://cdn.tailwindcss.com"></script>
  <script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.8/dist/htmx.min.js"></script>

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Dela+Gothic+One&family=Noto+Sans+JP:wght@100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Potta+One&display=swap" rel="stylesheet">

</head>
<body class="bg-gray-100 text-gray-900">

  <header class="bg-white p-6 shadow-lg">
    <div class="max-w-4xl mx-auto">
      <h1 class="text-3xl font-bold text-center">{{ _('Stampy') }}</h1>
    </div>
  </header>

  <!-- メニュー -->
  <nav class="fixed bottom-0 left-0 right-0 bg-white border-t-4 border-gray-200 shadow-2xl">
    <ul class="max-w-4xl mx-auto flex justify-around items-center p-4">
      <li class="inline-block text-center text-xs text-gray-700">
        <a href="{{ url_for('routes.home') }}">
          <img src="{{ url_for('static', filename='icons/home.svg') }}">
          <span>{{ _('ホーム') }}</span>
        </a>
      </li>
      <li class="inline-block text-center text-xs text-gray-700">
        <a href="{{ url_for('routes.talks') }}">
          <img src="{{ url_for('static', filename='icons/talk.svg') }}">
          <span>{{ _('トーク') }}</span>
        </a>
      </li>
      <li class="inline-block text-center text-xs text-gray-700">
        <a href="{{ url_for('routes.settings') }}">
          <img src="{{ url_for('static', filename='icons/setting.svg') }}">
          <span>{{ _('設定') }}</span>
        </a>
      </li>
    </ul>
  </nav>

  <main class="p-6">
    {% block content %}{% endblock %}
  </main>
</body>
</html>

templates/app/settings.html
{% extends "app/base.html" %}
{% block title %}Home{% endblock %}
{% block content %}

<div class="max-w-4xl mx-auto">
  <h1 class="text-3xl font-bold text-center">ホーム</h1>
</div>

<div class="max-w-4xl mx-auto p-6">
  <!-- myprofile -->
  <div class="bg-white rounded-3xl shadow-xl p-8 mb-8">
    <h2 class="text-2xl font-bold mb-6 text-gray-800">{{ _('プロフィール') }}</h2>
    <div class="flex items-center gap-6">
      <p class="text-3xl font-bold text-gray-900 mb-2">山田太郎</p>
      <p class="text-2xl">今日の気分：{mood_stamp}</p>
    </div>
  </div>

  <!-- friends -->
  <h2 class="text-2xl font-bold mb-6 text-gray-800">{{ _('友達') }}</h2>
  <div class="flex flex-col gap-6 bg-white rounded-3xl shadow-xl p-8">
    <div class="flex items-center gap-6">
      <p class="text-3xl font-bold text-gray-900 mb-2">山田太郎</p>
      <p class="text-2xl">今日の気分：{mood_stamp}</p>
    </div>
  </div>
</div>



{% endblock %}